Revert "easy-rating-dialog....again?"
This reverts commit b7479c7f5e467ea26712b8c995916d57247e49f9.

Causes crash, stacktrace :
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/afollestad/materialdialogs/AlertDialogWrapper$Builder;
                         E      at com.github.fernandodev.easyratingdialog.library.EasyRatingDialog.createDialog(EasyRatingDialog.java:155)
                         E      at com.github.fernandodev.easyratingdialog.library.EasyRatingDialog.tryShow(EasyRatingDialog.java:106)
                         E      at com.github.fernandodev.easyratingdialog.library.EasyRatingDialog.showIfNeeded(EasyRatingDialog.java:59)

Signed-off-by: Harsh Shandilya <msfjarvis@gmail.com>